### ISSUE TITLE
Put addon up for adoption?

### ISSUE THREAD

**Issue by patocallaghan** [adopted-ember-addons/ember-qunit-nice-errors#70]
When an original owner no longer has time to maintain the addon, there is a place where the addon can be "put up for adoption." [Melanie Sumner](https://github.com/MelSumner) has created [adopted-ember-addons](https://github.com/adopted-ember-addons). See the dedicated [#ember-adopted-addons](https://discord.com/channels/480462759797063690/525367494400278538) channel in the Ember Discord.

Would you consider allowing us to adopt ember-qunit-nice-errors so that the addon may continue to provide useful service to the community?

/cc @jmbejar

**Comment by SergeAstapov** [comment]
would be glad to help with addon support as one of engineers already was looking to Babel 7.x upgrade

**Comment by jmbejar** [comment]
Sincere apologies people! We have never made the choice to look for new maintainers, but this is the way to go 👍🏻

Let me get in touch with the Melanie as @patocallaghan suggested.

**Comment by backspace** [comment]
Seems like this could be closed, since adoption appears to have happened? 🤓
