### ISSUE TITLE
Publish security updates

### ISSUE THREAD

**Issue by svdsande** [adopted-ember-addons/ember-qunit-nice-errors#76]
Currently the latest release is version [1.2.0](https://github.com/adopted-ember-addons/ember-qunit-nice-errors/releases/tag/v1.2.0) which dates back to January 2018. Between then and now some commits were made to this repository, mostly regarding package updates. Some of these updates also resolved active security issues. Unfortunately these changes aren't published. Would it maybe be possible to create a new release from the current master branch? Therefore enabling consumers to update and benefit from these changes.

**Comment by knownasilya** [comment]
Will try to get to it this week if someone else doesn't first.

**Comment by svdsande** [comment]
@knownasilya Let me know if I could assist in any way
